<?php
add_action( 'wp_enqueue_scripts', 'test_ajax_scripts' ); 
// Register Ajax handler for action "test-ajax" 
add_action( 'wp_ajax_test-ajax', 'test_ajax_func' );
// Register Ajax handler for action "test-ajax" for users who are not logged in (hence the _nopriv) 
add_action( 'wp_ajax_nopriv_test-ajax', 'test_ajax_func' );

// Function to set up JavaScript stuff for the page
function test_ajax_scripts() {
	// Get the JavaScript file for this page template included on the page
    wp_enqueue_script( 'test-ajax', get_stylesheet_directory_uri() . '../js/test-ajax.js', array( 'jquery' ));	
	
	// Create some JavaScript variables that can be used in the .js file
    wp_localize_script( 'test-ajax', 'WordPressAjax', array(
        'ajaxurl'   => admin_url( 'admin-ajax.php' ),
        'nonce'     => wp_create_nonce( 'test-ajax-nonce' ))
    );
	
}

// Function that will get called when an Ajax request is submitted on the server 
function test_ajax_func() {
	// check nonce
	$nonce = $_POST['nonce']; 	
	if ( ! wp_verify_nonce( $nonce, 'test-ajax-nonce' ) )
		die ( 'You do not have permission to use this web service' );
		
	// generate the response
	$response = "<p><i>Generated by server-side code (in test-ajax-include.php) without a page refresh!</i></p><p>It looks like you clicked the button for <strong>" . $_POST['button'] . "</strong></p>";
 
	// response output
	header( "Content-Type: text/html" );
	echo $response;
 
	// IMPORTANT: don't forget to "exit"
	exit;
}

?>